package schoolProject;
// Generated Oct 4, 2018 10:30:23 AM by Hibernate Tools 5.1.8.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer idUser;
	private String lastname;
	private String firstname;
	private String age;
	private Character gender;

	public User() {
	}

	public User(String lastname, String firstname, String age, Character gender) {
		this.lastname = lastname;
		this.firstname = firstname;
		this.age = age;
		this.gender = gender;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

}
